spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

book-store:
  localization:
    default-language: en
    supported-languages:
      - en
      - uk
  frontend:
    base-url: ${FRONTEND_BASE_URL}
    verify-uri: ${FRONTEND_VERIFY_URI:/verify}
    employee-verify-uri: ${FRONTEND_EMPLOYEE_VERIFY_URI:/employees/verify}
    reset-password-uri: ${FRONTEND_RESET_PASSWORD_URI:/reset-password}
  auth:
    cors:
      enabled: true
      allowed-origins:
        - ${FRONTEND_BASE_URL}
    token:
      cooldown-period-ms: ${TOKEN_COOLDOWN_PERIOD_MS:180000}
      reset-password-expiration-ms: ${TOKEN_RESET_PASSWORD_EXPIRATION_MS:900000}
      verify-expiration-ms: ${TOKEN_VERIFY_EXPIRATION_MS:86400000}
    jwt:
      refresh-token:
        expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}
        grace-period-ms: ${JWT_REFRESH_TOKEN_GRACE_PERIOD_MS:15000}
      access-token:
        expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
        secret-key: ${JWT_SECRET}
  scheduler:
    cleanup:
      cart-ttl-days: 30
      unverified-user-ttl-days: ${UNVERIFIED_USER_TTL_DAYS:7}
      cron: ${CLEANUP_CRON:0 0 0 * * *}
