services:
  book-store-server:
    container_name: book-store-server
    image: book-store-server:dev
    build:
      context: ..
      dockerfile: java-server/Dockerfile
    env_file:
      - ../environments/.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"

  book-store-client:
    container_name: book-store-client
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../web-client:/app
    command: sh -c "npm install && npm run dev"
    env_file:
      - ../environments/.env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
